apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqldb-storage
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp2
  resources:
    requests:
      storage: 10Gi
