#Used for troubleshooting

apiVersion: v1
kind: Pod
metadata:
    name: guacamole-helper
    namespace: guacamole
spec:
    containers:
        - name: guacamole-helper
          image: d2iqshadowbq/guacd-helper:v1.1.0
          command: ["/bin/sh", "-c", "--"]
          args: ["while :; do :; done & kill -STOP $! && wait $!"]
          imagePullPolicy: Always
          env:
              - name: MYSQL_PORT
                value: "3306"
              - name: MYSQL_HOSTNAME
                value: "guacamole-db"
              - name: MYSQL_DATABASE
                valueFrom:
                    secretKeyRef:
                        name: guacamole
                        key: database
              - name: MYSQL_USER
                valueFrom:
                    secretKeyRef:
                        name: guacamole
                        key: user_login
              - name: MYSQL_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: guacamole
                        key: user_password
          resources:
              requests:
                  memory: "64Mi"
                  cpu: "250m"
              limits:
                  memory: "256Mi"
                  cpu: "750m"
